# Generated by Django 2.2.6 on 2019-10-31 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_restaurante_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prato',
            name='foto',
            field=models.ImageField(upload_to='imagens1/'),
        ),
    ]
